/* Implementing some queries */

SELECT NAME FROM EMPLOYEE;

SELECT NAME, NAME, NAME, NAME FROM EMPLOYEE;

SELECT NAME, EMPCODE FROM EMPLOYEE ORDER BY SALARY;

SELECT NAME, SALARY, SALARY+500, SALARY-5000 FROM EMPLOYEE;

SELECT SUM(SALARY) FROM EMPLOYEE;

SELECT MIN(SALARY) FROM EMPLOYEE;

SELECT MAX(SALARY) FROM EMPLOYEE;

SELECT NAME, SALARY, SALARY*1.5 AS INCREASED_SALARY FROM EMPLOYEE;

/*Make a copy of employee table as “NewEmp” table with all records.*/

CREATE TABLE NEWEMP AS SELECT * FROM EMPLOYEE;

SELECT * FROM NEWEMP;

/*Make a copy of employee table as “Emp2” table with no (Zero) records.*/

CREATE TABLE EMP2 AS SELECT * FROM EMPLOYEE WHERE 1=0;

SELECT * FROM EMPLOYEE;

SELECT * FROM NEWEMP;

SELECT * FROM EMP2;

DESC EMPLOYEE;

DESC NEWEMP;

DESC EMP2;

/*Create a new table “MyTable” from employee table with only Name and Salary columns.*/

CREATE TABLE MYTABLE AS SELECT NAME, SALARY FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM MYTABLE;

SELECT * FROM TAB;

COMMIT;

/*Drop the columns “name” and “empcode” from NewEmp table.*/

ALTER TABLE NEWEMP DROP COLUMN NAME;

ALTER TABLE NEWEMP DROP COLUMN EMPCODE;

SELECT * FROM NEWEMP;

/*Truncate the “Mytable” table.*/

TRUNCATE TABLE MYTABLE;

SELECT * FROM MYTABLE;

ROLLBACK;

SELECT * FROM MYTABLE;

/*Drop the “MyTable” table.*/

DROP TABLE MYTABLE;

SELECT * FROM MYTABLE;

ROLLBACK;

SELECT * FROM MYTABLE;

/*list of the total tables*/

SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'USER_NAME';

COMMIT;